name: Run Tests
on: push
env:
  PYTHON_VERSION: 3.12.5

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Configure AWS credentials (using GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ secrets.REGION }}

      - name: Install dependencies and run tests for get-function
        run: |
          cd get-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover -v

      - name: Install dependencies and run tests for put-function
        run: |
          cd ../put-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover -v
