name: main
on: push
env:
  PYTHON_VERSION: 3.12.5

jobs:
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step to check out the repository
      - uses: actions/checkout@v3

      # Set up Python environment with the correct version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      # Install dependencies and run tests for get-function
      - name: Install dependencies and run get-function tests
        run: |
          cd get-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest test_functions.py -v

      # Run tests for the put-function
      - name: Run put-function tests
        run: |
          cd put-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest test_functions.py -v
