name: main
on: push
env:
  PYTHON_VERSION: 3.12.5
jobs:
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # Step to check out the repository
      - uses: actions/checkout@v3

      # Set up Python environment with the correct version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Create the AWS credentials and config file
      - name: Set up AWS Credentials
        run: |
          cp aws-config/credentials ~/.aws/credentials
          cp aws-config/config ~/.aws/config
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        shell: bash

      # Install required Python packages (including boto3)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r get-function/requirements.txt

      # Run tests for the get-function
      - name: Test get-function
        run: |
          cd get-function
          python -m unittest discover -v
          cd ..

      # Run tests for the put-function
      - name: Test put-function
        run: |
          cd put-function
          python -m unittest discover -v
          cd ..
